version: '3.1',
services: 
    nginx: 
        image: nginx:kaikeba 
        ports: -80:80


app-pm2: 
    container_name: app-pm2 
    #构建容器 
    build: . 
    # volumes: 
    # - .:/usr/src/app 
    ports: 
      -"3000:3000"
